Repository MANVSim/MANVSim, pull requests merged in 2024-06, with the labels that each got.

#97 bug-fix, test update
  server/executions/api/actions.py
  server/executions/api/lobby.py
  server/executions/entities/player.py
  server/executions/run.py
  server/executions/tests/api/test_action.py
  server/executions/tests/api/test_lobby.py
  server/executions/tests/conftest.py
  server/executions/tests/entities/test_location.py
  server/executions/tests/entities/test_resource.py
Labels: bug, backend

#100 add test to pipeline
  .github/workflows/server.yml
Labels: backend

#101 Refactor: Use Mapped Columns
  server/Pipfile.lock
  server/app.py
  server/main.py
  server/migrations/versions/525315554799_.py
  server/migrations/versions/b9b45e484246_.py
  server/models.py
Labels: backend, database

#106 update entities
  doc/server/entity_relation_runtime.svg
  server/executions/api/location.py
  server/executions/entities/location.py
  server/executions/entities/stategraphs/activity_diagram.py
  server/executions/services/entityloader.py
  server/executions/tests/entities/dummy_entities.py
Labels: backend

#107 Bug/server/103 applicationjson fr alle post requests
  server/app.py
  server/app_config.py
  server/dbsetup.py
  server/execution/api/actions.py
  server/execution/api/lobby.py
  server/execution/api/location.py
  server/execution/api/patient.py
  server/execution/tests/api/test_action.py
  server/execution/tests/conftest.py
  server/main.py
  server/models.py
Labels: bug, backend

#108 Bug/server/98 no mutation on objects
  server/execution/api/actions.py
  server/execution/entities/resource.py
  server/execution/tests/api/test_action.py
  server/execution/tests/conftest.py
  server/execution/tests/entities/dummy_entities.py
Labels: bug, backend

#110 Server: rename dicts, fix types, and entity loader test
  .github/workflows/server.yml
  server/execution/api/lobby.py
  server/execution/entities/execution.py
  server/execution/run.py
  server/execution/services/entityloader.py
  server/execution/tests/api/test_action.py
  server/execution/tests/api/test_lobby.py
  server/execution/tests/conftest.py
  server/execution/tests/entities/test_location.py
  server/execution/tests/services/__init__.py
  server/execution/tests/services/test_entityloader.py
  server/execution/utils/util.py
  server/migrations/versions/53a3f9ceba2d_.py
  server/models.py
Labels: backend

#116 Feature/server/111 define more detailed patientstatus
  server/execution/api/actions.py
  server/execution/entities/action.py
  server/execution/entities/patient.py
  server/execution/entities/stategraphs/activity_diagram.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/services/entityloader.py
  server/execution/tests/api/test_action.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/tests/entities/test_activity_diagram.py
  server/execution/tests/services/test_entityloader.py
Labels: enhancement, backend

#115 Server: check new tans against existing ones
  server/utils/tans.py
Labels: bug, backend

#114 Add Web Frontend using dummy data
  server/Pipfile
  server/Pipfile.lock
  server/app.py
  server/dbsetup.py
  server/migrations/versions/06903a4c678d_.py
  server/models.py
  server/web/__init__.py
  server/web/api/register.py
  server/web/api/test_data.py
  server/web/setup.py
  web/.eslintrc.cjs
  web/.prettierrc.json
  web/README.md
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/api.tsx
  web/src/config.ts
  web/src/contexts/auth.tsx
  web/src/contexts/csrf.tsx
  web/src/contexts/use.tsx
  web/src/error-page.tsx
  web/src/main.tsx
  web/src/routes/execution.tsx
  web/src/routes/index.tsx
  web/src/routes/login.css
  web/src/routes/login.tsx
  web/src/routes/root.tsx
  web/src/routes/scenario.tsx
  web/src/storage.ts
  web/src/types.tsx
  web/src/utils.tsx
  web/vite.config.ts
Labels: enhancement, backend, web

#120 feat(app) #69: add actions for ios and android
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
Labels: app

#132 Feature/server/131 server add requested attributes
  server/dbsetup.py
  server/execution/api/lobby.py
  server/execution/entities/execution.py
  server/execution/entities/player.py
  server/execution/run.py
  server/execution/services/entityloader.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/tests/services/test_entityloader.py
  server/migrations/versions/985b081ce4e4_.py
  server/models.py
Labels: enhancement, backend

#125 Backend for scenario and execution views
  server/Pipfile
  server/Pipfile.lock
  server/models.py
  server/utils/flask.py
  server/web/api/register.py
  web/src/api.tsx
  web/src/components/CsrfForm.tsx
  web/src/routes/execution.tsx
  web/src/routes/login.tsx
  web/src/routes/scenario.tsx
  web/src/types.ts
Labels: backend, web

#133 Feature/server/124 add execution notification into game
  doc/api/api.yaml
  server/app.py
  server/execution/api/action.py
  server/execution/api/notification.py
  server/execution/entities/execution.py
  server/execution/tests/api/test_notification.py
  server/execution/web/notification.py
  server/execution/web/setup.py
Labels: enhancement, backend

#144 Update react-router-bootstrap to 0.26.3
  web/package-lock.json
  web/package.json
Labels: bug, web
