Repository MANVSim/MANVSim, pull requests merged in 2024-07, with the labels that each got.

#142 remove hard-coded test-data, organize test-data, fix test-methods
  server/README.md
  server/execution/entities/stategraphs/patientstate.py
  server/execution/run.py
  server/execution/tests/api/test_action.py
  server/execution/tests/api/test_lobby.py
  server/execution/tests/api/test_notification.py
  server/execution/tests/conftest.py
  server/execution/tests/entities/dummy_entities.py
  server/vars.py
Labels: backend

#148 feat #147: only trigger web action on web changes
  .github/workflows/build-web.yml
Labels: web

#139 Chore: Add pyright to CI
  .github/workflows/server.yml
  server/Pipfile
  server/Pipfile.lock
  server/app.py
  server/dbsetup.py
  server/execution/api/action.py
  server/execution/api/location.py
  server/execution/entities/location.py
  server/execution/entities/patient.py
  server/execution/entities/player.py
  server/execution/entities/role.py
  server/execution/entities/stategraphs/activity_diagram.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/services/entityloader.py
  server/execution/tests/entities/test_patient_state.py
  server/execution/tests/services/test_entityloader.py
  server/execution/utils/timeoutlock.py
  server/execution/web_api/lobby.py
  server/migrations/env.py
  web/package-lock.json
Labels: enhancement

#163 generate secrets automatically
  server/app.py
  server/vars.py
Labels: backend

#160 Server: Static media access
  server/.gitignore
  server/app.py
  server/dbsetup.py
  server/media/__init__.py
  server/media/media_api.py
  server/media/static/rucksack_blau.jpg
  server/media/static/rucksack_rot.jpg
  server/media/static/tasche_blau.jpg
  server/media/static/tasche_ekg.jpg
  server/media/static/tasche_rot.jpg
  server/media/static/tasche_sichtung.jpg
  server/media/tests/__init__.py
  server/media/tests/conftest.py
  server/media/tests/test_media.py
Labels: enhancement, backend

#165 Server: Media API documentation
  doc/server/media/README.md
  doc/server/media/media_api.yml
Labels: documentation, backend

#158 feat(server): basic event logging
  server/event_logging/__init__.py
  server/event_logging/event.py
  server/execution/api/action.py
  server/execution/api/location.py
  server/execution/api/patient.py
  server/execution/web_api/lobby.py
  server/migrations/versions/2aaa2c1e5ed6_.py
  server/migrations/versions/ed494d5ea048_.py
  server/models.py
Labels: enhancement, backend, database

#167 Server: Additional Images
  server/dbsetup.py
  server/media/static/README.md
  server/media/static/ktw_drk.png
  server/media/static/nef_sh.png
  server/media/static/rtw_sh.png
Labels: documentation, enhancement, backend

#166 Unify Patient/ location arrive/leave
  server/execution/api/location.py
  server/execution/api/patient.py
Labels: enhancement, backend

#161 Feature/server/159 endpoint to load already active executions for web
  doc/web/Design Vorlage Scenario Selector.svg
  server/dbsetup.py
  server/execution/entities/patient.py
  server/execution/services/entityloader.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/tests/services/test_entityloader.py
  server/execution/web_api/lobby.py
  server/migrations/versions/06903a4c678d_.py
  server/migrations/versions/2aaa2c1e5ed6_.py
  server/migrations/versions/985b081ce4e4_.py
  server/migrations/versions/c61745be7662_.py
  server/migrations/versions/ed494d5ea048_.py
  server/models.py
  server/vars.py
Labels: enhancement, backend, database

#168 Feature/web/126 create new players on execution page
  server/Pipfile
  server/Pipfile.lock
  server/administration/web_api/login.py
  server/execution/entities/execution.py
  server/execution/services/entityloader.py
  server/execution/web_api/lobby.py
  server/scenario/web_api/scenario.py
  server/utils/decorator.py
  server/vars.py
  web/src/api.tsx
  web/src/routes/execution.css
  web/src/routes/execution.tsx
  web/src/routes/scenario.tsx
  web/src/types.ts
Labels: enhancement, backend, database, web

#175 Feature/app/174 login api and persistence
  app/lib/l10n/de.arb
  app/lib/main.dart
  app/lib/models/tan_user.dart
  app/lib/screens/login_screen.dart
  app/lib/screens/name_screen.dart
  app/lib/screens/start_screen.dart
  app/lib/screens/tan_screen.dart
  app/lib/services/api_service.dart
  app/lib/widgets/logout_button.dart
  app/lib/widgets/tan_input.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: app

#178 server #177 dont try to read JWT in OPTIONS request
  server/execution/api/setup.py
Labels: bug, backend

#173 Feature/web/test active scenarios
  server/Pipfile
  server/Pipfile.lock
  server/administration/web_api/login.py
  server/dbsetup.py
  server/execution/entities/execution.py
  server/execution/services/entityloader.py
  server/execution/utils/util.py
  server/execution/web_api/lobby.py
  server/scenario/web_api/scenario.py
  server/utils/decorator.py
  server/utils/tans.py
  server/vars.py
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/api.tsx
  web/src/assets/MANV.png
  web/src/config.ts
  web/src/contexts/csrf.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/routes/execution.css
  web/src/routes/execution.tsx
  web/src/routes/index.tsx
  web/src/routes/scenario.css
  web/src/routes/scenario.tsx
  web/src/types.ts
Labels: enhancement, backend, web

#187 limit actions to role power
  server/dbsetup.py
  server/execution/api/action.py
  server/execution/tests/api/test_action.py
  server/execution/tests/conftest.py
  server/execution/utils/util.py
  server/execution/web_api/lobby.py
Labels: enhancement, backend

#189 Refactor(web): Component Structure
  server/scenario/web_api/scenario.py
  web/src/App.css
  web/src/App.tsx
  web/src/api.tsx
  web/src/api/auth.ts
  web/src/api/execution.ts
  web/src/api/index.ts
  web/src/api/player.ts
  web/src/api/templates.ts
  web/src/api/utils.ts
  web/src/components/CsrfForm.tsx
  web/src/components/ExecutionStatus.tsx
  web/src/components/NavLink.tsx
  web/src/components/PlayerStatus.tsx
  web/src/components/StatusIcon.tsx
  web/src/components/TanCard.css
  web/src/components/TanCard.tsx
  web/src/components/templateEntry.css
  web/src/components/templateEntry.tsx
  web/src/contexts/auth.tsx
  web/src/contexts/csrf.tsx
  web/src/hooks/index.ts
  web/src/main.tsx
  web/src/routes/error-page.tsx
  web/src/routes/execution.css
  web/src/routes/execution.tsx
  web/src/routes/executionList.css
  web/src/routes/executionList.tsx
  web/src/routes/index.css
  web/src/routes/index.tsx
  web/src/routes/login.tsx
  web/src/routes/root.tsx
  web/src/routes/scenario.css
  web/src/routes/scenario.tsx
  web/src/services/auth.ts
  web/src/services/storage.ts
  web/src/types.ts
  web/src/utils.tsx
Labels: enhancement, web

#192 Server: add default image
  server/dbsetup.py
  server/execution/tests/entities/dummy_entities.py
  server/media/static/no_image.png
Labels: enhancement, backend

#190 add notification input + display
  server/execution/services/entityloader.py
  server/execution/web_api/lobby.py
  web/src/api/execution.ts
  web/src/components/templateEntry.tsx
  web/src/routes/execution.css
  web/src/routes/execution.tsx
  web/src/routes/executionList.css
  web/src/routes/executionList.tsx
  web/src/types.ts
Labels: enhancement, web

#196 Server: code simplifications and clean up
  server/execution/entities/action.py
  server/execution/entities/execution.py
  server/execution/entities/location.py
  server/execution/entities/patient.py
  server/execution/entities/performed_action.py
  server/execution/entities/player.py
  server/execution/entities/resource.py
  server/execution/entities/role.py
  server/execution/entities/scenario.py
  server/execution/entities/stategraphs/activity_diagram.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/services/entityloader.py
  server/execution/tests/entities/dummy_entities.py
  server/utils/tans.py
Labels: backend

#198 Server: Configurable dict/json attributes
  server/execution/entities/action.py
  server/execution/entities/execution.py
  server/execution/entities/location.py
  server/execution/entities/patient.py
  server/execution/entities/performed_action.py
  server/execution/entities/player.py
  server/execution/entities/resource.py
  server/execution/entities/role.py
  server/execution/entities/scenario.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/web_api/lobby.py
Labels: enhancement, backend
