Repository MANVSim/MANVSim, pull requests merged in 2024-10, with the labels that each got.

#435 Feature/server/434 server update and enhance documentation
  README.md
  doc/server/entity/entity_relation_runtime.svg
  server/README.md
  server/administration/__init__.py
  server/administration/web_api/__init__.py
  server/execution/__init__.py
  server/execution/entities/__init__.py
  server/execution/entities/stategraphs/__init__.py
  server/execution/services/__init__.py
  server/execution/utils/__init__.py
  server/execution/web_api/__init__.py
  server/media/__init__.py
  server/scenario/__init__.py
  server/scenario/web_api/__init__.py
  server/utils/__init__.py
Labels: documentation

#439 create inmemory db for test, separate client/app fixtures
  .github/workflows/server.yml
  server/Pipfile.lock
  server/app.py
  server/conftest.py
  server/dbsetup.py
  server/execution/tests/api/test_action.py
  server/execution/tests/api/test_lobby.py
  server/execution/tests/api/test_location.py
  server/execution/tests/api/test_notification.py
  server/execution/tests/api/test_setup.py
  server/execution/tests/entities/test_location.py
  server/execution/tests/entities/test_resource.py
  server/execution/tests/services/test_entityloader.py
  server/execution/tests/web_api/test_lobby.py
  server/media/tests/test_media_api.py
  server/scenario/tests/test_scenario.py
Labels: enhancement, backend, database

#438 fix vulnerabilities
  web/package-lock.json
  web/package.json
Labels: web

#440 Update server docs
  README.md
  doc/server/README.md
  doc/web/README.md
  doc/web/design/general-editor/Mockup General Editor - Maßnahme Edit.jpg
  doc/web/design/general-editor/Mockup General Editor - Maßnahme Übersicht.jpg
  doc/web/design/general-editor/Mockup General Editor - Maßnahmen Liste.jpg
  doc/web/design/general-editor/Mockup General Editor - RVO Edit.jpg
  doc/web/design/general-editor/Mockup General Editor - RVO Übersicht.jpg
  doc/web/design/general-editor/Mockup General Editor - RVOs Liste.jpg
  doc/web/design/general-editor/Mockup General Editor - Ressource Edit.jpg
  doc/web/design/general-editor/Mockup General Editor - Ressource Übersicht.jpg
  doc/web/design/general-editor/Mockup General Editor - Ressourcen Liste.jpg
  doc/web/design/scenario-editor/Mockup Scenario Editor Ansicht v1.jpg
  doc/web/design/scenario-editor/Mockup Scenario Editor Ansicht v2.jpg
  doc/web/design/template_scenario_selector.svg
  server/README.md
Labels: documentation, backend

#446 Add README for web component
  web/README.md
Labels: web
