Repository MANVSim/MANVSim, pull requests merged in 2024-08, with the labels that each got.

#199 28 add qrcode scan widget
  app/android/app/build.gradle
  app/android/gradle/wrapper/gradle-wrapper.properties
  app/lib/screens/login_screen.dart
  app/lib/screens/patient_select_screen.dart
  app/lib/screens/qr_screen.dart
  app/lib/widgets/tan_input.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: app

#206 switch travel time to arrival time of a player, update test
  doc/server/api_game/api.yaml
  server/execution/api/lobby.py
  server/execution/entities/player.py
  server/execution/tests/api/test_lobby.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/web_api/lobby.py
Labels: enhancement, backend

#204 Feature/server/197 server start activitydiagrams of patients if execution is activated
  server/execution/entities/execution.py
  server/execution/entities/patient.py
  server/execution/entities/scenario.py
  server/execution/entities/stategraphs/activity_diagram.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/tests/conftest.py
  server/execution/tests/services/test_entityloader.py
  server/execution/tests/web_api/__init__.py
  server/execution/tests/web_api/test_lobby.py
  server/execution/web_api/lobby.py
Labels: enhancement, backend

#211 Feature/server/183 server implement multi media data type
  doc/server/api_media/README.md
  server/dbsetup.py
  server/execution/entities/action.py
  server/execution/entities/execution.py
  server/execution/entities/location.py
  server/execution/entities/patient.py
  server/execution/entities/resource.py
  server/execution/services/entityloader.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/tests/entities/test_location.py
  server/execution/tests/entities/test_resource.py
  server/execution/tests/services/test_entityloader.py
  server/media/media_data.py
  server/migrations/versions/e25eeba89926_.py
  server/models.py
Labels: enhancement, backend

#216 Game API: update picture ref to media ref
  doc/server/api_game/api.yaml
Labels: documentation, backend

#223 Feature/server/214 implement multi media datatype in results of actions
  .github/workflows/server.yml
  doc/server/api_media/README.md
  doc/server/api_media/media_api.yml
  server/conftest.py
  server/dbsetup.py
  server/execution/api/action.py
  server/execution/entities/stategraphs/activity_diagram.py
  server/execution/entities/stategraphs/patientstate.py
  server/execution/tests/api/test_action.py
  server/execution/tests/api/test_lobby.py
  server/execution/tests/api/test_notification.py
  server/execution/tests/api/test_setup.py
  server/execution/tests/entities/dummy_entities.py
  server/execution/tests/entities/test_activity_diagram.py
  server/execution/tests/entities/test_patient_state.py
  server/execution/tests/services/test_entityloader.py
  server/execution/tests/web_api/test_lobby.py
  server/media/media_api.py
  server/media/media_data.py
  server/media/tests/conftest.py
  server/media/tests/test_media.py
Labels: backend

#222 update take-from, add put-to, update api.yml
  doc/server/api_game/api.yaml
  server/event_logging/event.py
  server/execution/api/location.py
  server/execution/entities/location.py
Labels: enhancement, backend

#232 Feature/server/227 server define and implement user roles
  server/administration/web_api/login.py
  server/conftest.py
  server/dbsetup.py
  server/execution/web_api/lobby.py
  server/execution/web_api/notification.py
  server/main.py
  server/migrations/versions/07cf93704d1d_.py
  server/models.py
  server/scenario/web_api/scenario.py
  server/utils/decorator.py
  web/src/api/execution.ts
Labels: enhancement, backend, web

#234 feat(web): improve error handling
  web/src/routes/error-page.tsx
  web/src/routes/login.tsx
  web/src/routes/root.tsx
  web/src/services/auth.ts
Labels: enhancement, web

#240 Feature/server/231 media api return mediadata on 201
  doc/server/api_media/README.md
  doc/server/api_media/media_api.yml
  server/Pipfile
  server/event_logging/event.py
  server/execution/entities/execution.py
  server/execution/web_api/lobby.py
  server/media/media_api.py
  server/media/media_data.py
  server/media/tests/test_media_api.py
Labels: enhancement, backend

#245 Feature/server/243 separate inventory endpoint
  server/Pipfile.lock
  server/execution/api/location.py
  server/execution/tests/api/test_action.py
  server/execution/tests/api/test_location.py
  server/execution/tests/entities/test_location.py
Labels: bug, enhancement, backend

#246 DB: add vehicle mapping
  server/dbsetup.py
  server/migrations/versions/5d0abc223c6c_.py
  server/models.py
  server/scenario/web_api/data/location.py
Labels: enhancement, backend, database

#241 Media API: require scenario_admin for POST
  server/media/media_api.py
  server/media/tests/test_media_api.py
Labels: backend

#250 DB: update patient to scenario relation
  server/dbsetup.py
  server/execution/services/entityloader.py
  server/execution/tests/services/test_entityloader.py
  server/migrations/versions/670b07de71aa_.py
  server/models.py
  server/scenario/web_api/scenario.py
Labels: backend, database

#252 Server: update db relations and entity loading
  server/dbsetup.py
  server/execution/entities/location.py
  server/execution/services/entityloader.py
  server/execution/tests/services/test_entityloader.py
  server/migrations/versions/f5d3bad37316_.py
  server/models.py
Labels: backend, database

#230 Feature/server/169 scenario management
  server/dbsetup.py
  server/execution/entities/location.py
  server/execution/services/entityloader.py
  server/execution/tests/services/test_entityloader.py
  server/execution/web_api/lobby.py
  server/migrations/versions/3975b0c62bb6_.py
  server/models.py
  server/scenario/tests/__init__.py
  server/scenario/tests/test_action.py
  server/scenario/tests/test_scenario.py
  server/scenario/web_api/data/__init__.py
  server/scenario/web_api/data/action.py
  server/scenario/web_api/data/location.py
  server/scenario/web_api/data/patient.py
  server/scenario/web_api/data/resource.py
  server/scenario/web_api/scenario.py
  server/scenario/web_api/setup.py
  server/scenario/web_api/utils.py
Labels: enhancement, backend, database

#253 Feature/web/236 scenarioeditor web frontend implementation
  server/execution/web_api/lobby.py
  server/migrations/versions/72ac8e39e8a0_.py
  server/scenario/web_api/data/location.py
  server/scenario/web_api/data/patient.py
  server/scenario/web_api/scenario.py
  web/src/api/base-data.ts
  web/src/api/execution.ts
  web/src/components/scenario-data.css
  web/src/components/scenario-data.tsx
  web/src/components/searchbar.css
  web/src/components/searchbar.tsx
  web/src/components/templateEntry.tsx
  web/src/contexts/csrf.tsx
  web/src/main.tsx
  web/src/routes/base-data.tsx
  web/src/routes/execution.tsx
  web/src/routes/root.tsx
  web/src/routes/scenario-editor.tsx
  web/src/types.ts
Labels: enhancement, backend, web

#259 Bugfix/server/257 rework execution manager based on new db
  server/dbsetup.py
  server/execution/entities/execution.py
  server/execution/services/entityloader.py
  server/execution/tests/web_api/test_lobby.py
  server/execution/web_api/lobby.py
  server/migrations/versions/fdbf4b4340e2_.py
  server/models.py
  server/scenario/tests/test_scenario.py
  server/scenario/web_api/scenario.py
  web/src/routes/execution.tsx
Labels: backend, web

#261 Bug/server/254 put to endpoint location assignment required duplication of locations
  doc/server/api_game/api.yaml
  server/execution/api/location.py
  server/execution/entities/location.py
  server/execution/entities/player.py
  server/execution/tests/api/test_location.py
Labels: bug, backend

#269 #268 docker-compose; server in prod mode
  README.md
  compose-dev.yaml
  docker-compose.yaml
  server/Dockerfile
Labels: enhancement, backend

#262 Feature/server/205 server archive performed executions
  server/event_logging/__init__.py
  server/execution/api/action.py
  server/execution/api/location.py
  server/execution/api/patient.py
  server/execution/entities/event.py
  server/execution/entities/execution.py
  server/execution/tests/web_api/test_lobby.py
  server/execution/web_api/lobby.py
  server/migrations/versions/3037d9a7bdcd_.py
  server/models.py
Labels: enhancement, backend, database

#274 server/273 error runlocationtake to with empty to location ids
  doc/server/api_game/api.yaml
  server/execution/api/location.py
Labels: backend

#272 bug(app) #271: stop unnecessary builds
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
Labels: app
